name: Device Test Runner CI

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    code-quailiry:
        name: Code Quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                python-version: "3.14"

            - name: Install Poetry
              run: python -m pip install "poetry>=2,<3"

            - name: Install dependencies
              run: poetry install --no-interaction

            - name: Run pre-commit
              run: poetry run pre-commit run --all-files
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version:
              - "3.11"
              - "3.12"
              - "3.13"
        steps:
          - name: Checkout repository
            uses: actions/checkout@v7

          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v7
            with:
              python-version: ${{ matrix.python-version }}

          - name: Display Python version
            run: python --version

          - name: Install Poetry
            run: python -m pip install "poetry>=2,<3"

          - name: Install dependencies
            run: poetry install --no-interaction

          - name: Run Unit Test
            run: poetry run pytest tests/test_unit
    integration-tests:
        name: Integration Tests
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v7

          - name: Set up Python
            uses: actions/setup-python@v7
            with:
              python-version: "3.14"

          - name: Install Poetry
            run: python -m pip install "poetry>=2,<3"

          - name: Install dependencies
            run: poetry install --no-interaction

          - name: Run Integration Test
            run: poetry run pytest tests/test_integration
